const mongoose = require('mongoose');

const internalLinkSchema = new mongoose.Schema({
  text: { type: String, required: true },
  url: { type: String, required: true },
  category: { type: String, required: true }
}, { _id: false });

const externalLinkSchema = new mongoose.Schema({
  text: { type: String, required: true },
  url: { type: String, required: true },
  source: { type: String, required: true }
}, { _id: false });

const faqSchema = new mongoose.Schema({
  question: { type: String, required: true },
  answer: { type: String, required: true }
}, { _id: false });

const articleSchema = new mongoose.Schema({
  slug: {
    type: String,
    required: true,
    unique: true,
    index: true
  },
  title: {
    type: String,
    required: true
  },
  summary: {
    type: String,
    default: ''
  },
  content: {
    type: String,
    default: ''
  },
  expandedContent: {
    type: String,
    default: ''
  },
  category: {
    type: String,
    required: true,
    index: true
  },
  tags: [{
    type: String
  }],
  author: {
    type: String,
    default: 'Editorial Team'
  },
  imageUrl: {
    type: String,
    default: ''
  },
  heroImage: {
    type: String,
    default: ''
  },
  status: {
    type: String,
    enum: ['draft', 'published', 'archived'],
    default: 'published',
    index: true
  },
  source: {
    url: { type: String, default: '' },
    name: { type: String, default: '' }
  },
  metaTitle: {
    type: String,
    default: ''
  },
  metaDescription: {
    type: String,
    default: ''
  },
  focusKeyword: {
    type: String,
    default: ''
  },
  keywords: [{
    type: String
  }],
  internalLinks: [internalLinkSchema],
  externalLinks: [externalLinkSchema],
  imageAltTexts: [{
    type: String
  }],
  faq: [faqSchema],
  wordCount: {
    type: Number,
    default: 0
  },
  readabilityScore: {
    type: Number,
    default: 0
  },
  isExpanded: {
    type: Boolean,
    default: false
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  viewCount: {
    type: Number,
    default: 0
  },
  publishedAt: {
    type: Date,
    default: Date.now,
    index: true
  }
}, {
  timestamps: true
});

articleSchema.index({ title: 'text', summary: 'text', content: 'text' });
articleSchema.index({ category: 1, publishedAt: -1 });
articleSchema.index({ status: 1, publishedAt: -1 });

articleSchema.methods.toJSON = function() {
  const obj = this.toObject();
  obj.date = obj.publishedAt || obj.createdAt;
  return obj;
};

module.exports = mongoose.models.Article || mongoose.model('Article', articleSchema);
